### ISSUE TITLE
updates 

### ISSUE THREAD

**Issue by smangul1** [smangul1/ec#17]
Hi PARTH,

Any updates here?

 Please update the table 
here

https://github.com/smangul1/ec/wiki/Running-tools

with the tools and datasets you will run 
just you put your name and "todo"
For now take 2 or 3 

Serghei

**Comment by parthingle** [comment]
It seems like I don't have permission to run coral that I tried to run using this script:

```
  L1=(64 65 66 67 68 69 70 71 72 73)

   for i in `seq 0 9`; do
           /u/home/d/douglasy/coral-1.4.1/coral -fq /u/project/zarlab/ngcrawfo/igor/VIRAL_CORRECTION/tools/data/datasets_no_barcodes_no_index/SRR15439${L1[$i]}.fastq -o SRR155439$L1[$i]}_coral_output.fastq -p 1 -k 18
   done

```


This shell file run.sh is in my scratch directory /u/home/p/parthing/scratch/T2_Coral/

**Comment by parthingle** [comment]
Hey,, sorry I think I accidentally closed this issue
