### ISSUE TITLE
how you are obtaining the ground true for each reads from simulated data

### ISSUE THREAD

**Issue by smangul1** [smangul1/ec#18]
Let's discuss next time we talk
how you are obtaining the ground true for each reads from simulated data

**Comment by mandricigor** [comment]
Ground truth is obtained using the script

https://github.com/smangul1/ec/blob/master/scripts/ground_truth.py

**Comment by smangul1** [comment]
Do you assume any difference with the reference is an error? 
Did you simulate SNPs together with errors?
