### ISSUE TITLE
install bamsurgeon

### ISSUE THREAD

**Issue by smangul1** [smangul1/ec#22]
Who can help to install this tool?
https://github.com/adamewing/bamsurgeon

**Comment by brianhill11** [comment]
Installed at `/u/home/b/blhill/code/github/bamsurgeon`
If you need any tools that it depends on in your path, add `/u/home/b/blhill/code/bin` to your path. Let me know if there are any permissions issues.

**Comment by smangul1** [comment]
Great! I am using it now! Thanks, Brian!
