### ISSUE TITLE
 Racer and reptile

### ISSUE THREAD

**Issue by smangul1** [smangul1/ec#9]
-for S1 and T2, T3
-add instructions how to install and run
- finish Table S1 for  Racer and reptile

**Comment by smangul1** [comment]
Look here for kmer size
https://github.com/smangul1/ec

**Comment by smangul1** [comment]
Any updates here? For T2 please use : k=18 genome size=405000 log4(405*1000)X2=18

**Comment by kahsieh** [comment]
The S1 and T2 data are still running

**Comment by smangul1** [comment]
Can you please update the table by putting your name so we know that you are running 
https://github.com/smangul1/ec/wiki/Running-tools

**Comment by kahsieh** [comment]
Done

**Comment by smangul1** [comment]
great! can you please put the the path to the results in the table

**Comment by kahsieh** [comment]
Ok, I will do so once they finish running

**Comment by smangul1** [comment]
Can you put just you and an say "in progress"

**Comment by kahsieh** [comment]
Ok
